#!/bin/bash

LOG_DIR=$OPENSHIFT_LOG_DIR

directorios=$(find $OPENSHIFT_REPO_DIR/.openshift/action_hooks/jenkins  -type d)
for directory in $directorios ; do
    cd $directory
    for file in $(ls *.erb) ; do
       newFile=$(echo $file | sed "s/\.erb$//g")
       erb $file > $newFile
    done
done
cp -rf $OPENSHIFT_REPO_DIR/.openshift/action_hooks/jenkins/* $OPENSHIFT_DATA_DIR


cd $OPENSHIFT_REPO_DIR/.openshift/action_hooks/newrelic
. ./newrelic.sh > ${LOG_DIR}newrelic.log 2>&1